### ISSUE TITLE
tout effacer retire toutes les couches

### ISSUE THREAD

**Issue by 3nids** [VeriVD/qgis_VeriVD#1]
Il serait peut-être préférable de ne retirer que les couches/groupes ajoutées par le plugin?
on peut ajouter une "custom_property" aux couches pour les reconnaître lorsqu'on les ajoute

**Comment by Oltos** [comment]
Effectivement, je note l'idée et la transmettrais au groupe de travail.

**Comment by 3nids** [comment]
résolu dans le refactoring #2
