### ISSUE TITLE
114_VERIF_OD_surfaciqueErreur is GeometryCollection

### ISSUE THREAD

**Issue by 3nids** [VeriVD/qgis_VeriVD#11]
dans les données démo, la couche 114 est de type collection. Cela pose problème avec le code actuel.
Est-ce qu'on doit gérer ça ou c'est une erreur de ton côté?

<img width="715" alt="image" src="https://user-images.githubusercontent.com/127259/189814835-2cee05aa-04ba-4274-80e4-5a992f973719.png">

**Comment by Oltos** [comment]
[220624_Mens23_VD.zip](https://github.com/VeriVD/qgis_VeriVD/files/9576098/220624_Mens23_VD.zip)
Ok, je pense avoir réglé le problème (fichier ci-joint)
