### ISSUE TITLE
les champs du gpkg contiennent des lettres majuscules

### ISSUE THREAD

**Issue by 3nids** [VeriVD/qgis_VeriVD#12]
Les colonnes du gpkg contiennent des majuscules, par exemple: "Description" dans la couche`000_Checker_Point`.
Dans la config des couches, les colonnes pour la catégorisation sont indiquées en minuscule. Du coup, le plugin ne trouve pas le champ car la recherche respecte la casse des champs.
Je propose de n'utiliser que des minuscules afin de minimiser le risque d'erreur. Est-ce ok pour toi?

**Comment by Oltos** [comment]
Ok pour moi. Effectivement, en spatialite, les descriptions sont convertis automatiquement en minuscule par FME.
Du coup, tu veux que je change les descriptions du gpkg dans FME pour les avoir en minuscule ?

**Comment by 3nids** [comment]
je pense qu'il faudrait avoir tous les champs en minuscule idéalement.
mais au minimum ces champs là:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/127259/189828173-bea3609b-0178-45fd-8e39-f024d36b895b.png">

**Comment by Oltos** [comment]
Ok, je m'en occupe.

**Comment by Oltos** [comment]
[220624_Mens23_VD.zip](https://github.com/VeriVD/qgis_VeriVD/files/9554533/220624_Mens23_VD.zip)
J'ai modifié le script FME pour avoir des minuscules dans les noms d'attributs: fichier ci-joint).
C'est ok pour toi ?

**Comment by 3nids** [comment]
ça semble bon, merci
