### ISSUE TITLE
définition des couches de bases

### ISSUE THREAD

**Issue by 3nids** [VeriVD/qgis_VeriVD#18]
il semble que la définition des couches est répétée pour la couche "tous les topics" depuis les autres.
Il y a quelques mini différences (visibilité, requête SQL, …), mais j'imagine que c'est dû à des erreurs lors de modification (1 seule couche modifiée). Est-ce correct?

Même si ces différences sont voulues, je voudrais éviter la duplication du code et regrouper ce qui est possible.

**Comment by Oltos** [comment]
La coche Tous_les_topics permet le chargement d'un ensemble de couches de base d'un seul coup.
C'est assez pratique et très utilisé.
On a du adapter l'affichage de certaines couches pour permettre la superposition des couches.
C'est vrai que les modifications sont minimes peut être que l'on peut regrouper ces lignes.
