### ISSUE TITLE
couches justificatif

### ISSUE THREAD

**Issue by 3nids** [VeriVD/qgis_VeriVD#20]
```
CREATE TABLE 'justificatif_nogeometry' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT NOT NULL,
  statut TEXT NOT NULL,
  texte TEXT NOT NULL
)

CREATE TABLE 'justificatif_point' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  geometry POINT,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT NOT NULL,
  statut TEXT NOT NULL,
  texte TEXT NOT NULL
)

CREATE TABLE 'justificatif_line' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  geometry COMPOUNDCURVE,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT NOT NULL,
  statut TEXT NOT NULL,
  texte TEXT NOT NULL
)

CREATE TABLE 'justificatif_polygon' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  geometry CURVEPOLYGON,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT NOT NULL,
  statut TEXT NOT NULL,
  texte TEXT NOT NULL
)

INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_nogeometry','attributes');
INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_point','features');
INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES ('justificatif_point', 'geometry', 'POINT', 2056, 0, 0);
INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_line','features');
INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES ('justificatif_line', 'geometry', 'COMPOUNDCURVE', 2056, 0, 0);
INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_polygon','features');
INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES ('justificatif_polygon', 'geometry', 'CURVEPOLYGON', 2056, 0, 0);
```

**Comment by Oltos** [comment]
[220624_Mens23_VD.zip](https://github.com/VeriVD/qgis_VeriVD/files/10083345/220624_Mens23_VD.zip)
J'ai un peu galéré pour créer les tables avec DB Manager (c'est peut être lié à la version de Qgis).
Je suis pas très certain du résultat...

**Comment by 3nids** [comment]
désolé, j'avais oublié de remettre les champs "operateur" dans le SQL, tu en as besoin?
j'aurais encore un changement à faire c'est d'enlever la contrainte non null sur le champ topic

**Comment by Oltos** [comment]
Concernant le champ "operateur", mes collègues ont demandé de l'ajouter pour que l'on sache qui est à l'origine de la justification.

Ci dessous le geopackage modifié
[220624_Mens23_VD.zip](https://github.com/VeriVD/qgis_VeriVD/files/10083933/220624_Mens23_VD.zip)

**Comment by 3nids** [comment]
La dernière version ne fonctionne pas.
Est-ce que tu as exécuté les requêtes gpkg_contents et gpkg_geometry_columns?
peux-tu partager ici le code SQL comme ça on garde la trace?

**Comment by Oltos** [comment]
chez moi, DB manager n'accepte qu'une requête SQL à la fois.
Aussi une fois l'opération terminée, DB_manager ne se connecte plus au gpkg
![image](https://user-images.githubusercontent.com/18143333/203789950-3b177c49-2281-4560-852d-37f0fa6dcff1.png)
Mais la base existe bien, pour l'utiliser dans FME, j'ai du changer le paramètre: 
GEOPACKAGE reader: Directive '_ENFORCE_FOREIGN_KEY_INTEGRITY' has value 'NO'

Ci dessous la requête que j'ai utilisé:

CREATE TABLE 'justificatif_nogeometry' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT,
  statut TEXT NOT NULL,
  operateur TEXT,
  texte TEXT NOT NULL
)

CREATE TABLE 'justificatif_point' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  geometry POINT,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT,
  statut TEXT NOT NULL,
  operateur TEXT,
  texte TEXT NOT NULL
)

CREATE TABLE 'justificatif_line' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  geometry COMPOUNDCURVE,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT,
  statut TEXT NOT NULL,
  operateur TEXT,
  texte TEXT NOT NULL
)

CREATE TABLE 'justificatif_polygon' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  geometry CURVEPOLYGON,
  session TEXT NOT NULL,
  layer TEXT NOT NULL,
  topic TEXT,
  statut TEXT NOT NULL,
  operateur TEXT,
  texte TEXT NOT NULL
)

INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_nogeometry','attributes');
INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_point','features');
INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES ('justificatif_point', 'geometry', 'POINT', 2056, 0, 0);
INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_line','features');
INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES ('justificatif_line', 'geometry', 'COMPOUNDCURVE', 2056, 0, 0);
INSERT INTO gpkg_contents (table_name, data_type) values ('justificatif_polygon','features');
INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES ('justificatif_polygon', 'geometry', 'CURVEPOLYGON', 2056, 0, 0);

**Comment by Oltos** [comment]
[Justificatif.zip](https://github.com/VeriVD/qgis_VeriVD/files/10084836/Justificatif.zip)
[220624_Mens23_VD.zip](https://github.com/VeriVD/qgis_VeriVD/files/10084846/220624_Mens23_VD.zip)

Au cas ou il y a eu erreur de saisie, j'ai relancé la manip et te joint la table produite avec DB_manager et le résultat FME

**Comment by 3nids** [comment]
ça l'air de fonctionner!
