### ISSUE TITLE
couches introuvables

### ISSUE THREAD

**Issue by 3nids** [VeriVD/qgis_VeriVD#21]
le plugin essaye de charger sans succès ces couches:
007_itf_co_poselement_conduite
005_itf_no_pos_lieudit
 007_itf_co_element_conduite

est-ce attendu?

**Comment by Oltos** [comment]
Il s'agit des couches contenant les conduites LITC (plus de 50bars). Elles traversent le canton de Vaud mais il y en a peu ce qui fait qu'il est assez rare que des données soient présentes (FME ne produit normalement pas de couche vide).
