### ISSUE TITLE
Version 2.0.0-beta1

### ISSUE THREAD

**Issue by Oltos** [VeriVD/qgis_VeriVD#22]
Ne fonctionne pas chez moi
![image](https://user-images.githubusercontent.com/18143333/203831763-94a6b77e-d3e9-4588-9e7a-dbaffa2d56e7.png)

**Comment by 3nids** [comment]
@Oltos voilà https://github.com/VeriVD/qgis_VeriVD/releases/tag/2.0.0-beta2
