### ISSUE TITLE
Les lignes justifiées dans onglet iliValidator et checker

### ISSUE THREAD

**Issue by Oltos** [VeriVD/qgis_VeriVD#26]
Les objets lignes justifiées n'apparaissent pas dans les onglets iliValidator et checker

**Comment by 3nids** [comment]
comment s'appellent les couches lignes pour checker et ilivalidator?
je ne les avais pas dans l'exemple:
![image](https://user-images.githubusercontent.com/127259/207076894-7eae7d5e-4404-4f4e-aab4-7c135ffecdd4.png)

**Comment by Oltos** [comment]
Il s'agit de 000_Checker_Surface et 000_iliValidator_Surface, malgré leurs noms ils sortent en ligne.
Je te joins aussi une nouvelle version du qml pour les lignes car la version précédente insérait trop d'espacement dans la légende.

**Comment by Oltos** [comment]
[justificatif_lignes.zip](https://github.com/VeriVD/qgis_VeriVD/files/10209481/justificatif_lignes.zip)

**Comment by 3nids** [comment]
ça devrait être corrigé avec ça https://github.com/VeriVD/qgis_VeriVD/commit/c03ac0576d8cb683ba2289bdce74a3ed8e3a7411
tu peux tester la dernière beta

**Comment by Oltos** [comment]
J'ai testé, c'est ok. Merci
